### PR TITLE
Case sensitiveness, Interfaced objects, Anonymous filters

### PR DESCRIPTION
**Pull request by mrsw**
Hi Daniele,
I made some changes to allow keywords and variable names to be used regardless case sensitiveness, added a simple support for interfaced objects (now you can use SetData method to pass an interface).
I need to evaluate some expressions in if statements, is this feature planned and if so, timing?
Cheers.

### CODE REVIEW

**Comment by danieleteti** [comment]
Hi Carlo, thank you for your contributions. However, I think you started your on an old version because there are conflicts. Can you resolved those and check that unit tests are still OK in a subsequent PR? 
Thank you

**Comment by mrsw** [comment]
Hi Daniele,
I solved conflicts but I cannot make tests because the test application has some code problems, but the changes works in my application.
Let me know.

**Comment by mrsw** [comment]
The error is on line 117 of templateprounittests.dpr.
I solved the problem in my local copy this way:

var lTestScriptsFolder := TPath.Combine(ExtractFilePath(GetModuleName(HInstance)), '..') + '\test_scripts';

Now tests seem to work, 3 test are not passed but I think it's correct.

**Comment by danieleteti** [comment]
Carlo, I've just merged your changes, added a specific unit test and did some furter modification to make iterator names case insensitive too.
Please, check with your code to see if something is broken.
Thanks

**Pull request merged**
